services:
#  ogmios:
#    image: cardanosolutions/ogmios:v6.10.0
#    container_name: ogmios
#    ports:
#      - "1337:1337"
#    command: [
#      "--host", "0.0.0.0",
#      "--node-socket", "/ipc/node.socket",
#      "--node-config", "/config/cardano-node/config.json"
#    ]
#    volumes:
#      - /home/dat/Desktop/try-cardano-node/cardano-node-10.1.3-linux/node.socket:/ipc/node.socket # Mount the Cardano Node socket
#      - /home/dat/Desktop/try-cardano-node/cardano-node-10.1.3-linux/share/preprod:/config/cardano-node # Mount the Cardano Node config file
#    environment:
#      - OGMIOS_NODE_SOCKET_PATH=/ipc/node.socket
#      - OGMIOS_PORT=1337
#      - OGMIOS_HOST=0.0.0.0


#  ogmios:
#      image: cardanosolutions/ogmios:v6.10.0
#      restart: on-failure
#      command: [
#        "--host", "0.0.0.0",
#        "--node-socket", "/ipc/node.socket",
#        "--node-config", "/config/cardano-node/config.json"
#      ]
#      volumes:
#        - /home/dat/Desktop/try-cardano-node/cardano-node-10.1.3-linux/share/preprod:/config/cardano-node
#        - /home/dat/Desktop/try-cardano-node/cardano-node-10.1.3-linux:/ipc
#      ports:
#        - ${OGMIOS_PORT:-1337}:1337

   ogmios:
      image: cardanosolutions/ogmios:v6.10.0
      restart: always
      command:
        [
          "--host",
          "0.0.0.0",
          "--node-socket",
          "/node.socket",
          "--node-config",
          "/node-configs/config.json",
        ]
      ports:
        - 1337:1337
      volumes:
        - type: bind
          source: /home/dat/Desktop/try-cardano-node/cardano-node-10.1.3-linux/node.socket
          target: /node.socket
        - type: bind
          source: /home/dat/Desktop/try-cardano-node/cardano-node-10.1.3-linux/share/preprod
          target: /node-configs